replicaCount: 1
image:
  repository: 012345678901.dkr.ecr.us-west-2.amazonaws.com/develop/mediawiki
  tag: "latest"

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 1000m
    memory: 2048Mi
  requests:
    cpu: 1000m
    memory: 2048Mi